# Generated by Django 4.0.6 on 2025-04-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_dummyuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
