# Generated by Django 4.0.6 on 2025-04-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_managers_remove_user_username'),
    ]

    operations = [
    ]
