# Generated by Django 4.0.6 on 2022-07-26 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=126)),
                ('country', models.CharField(max_length=126)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_proposal', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('note', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DINE', 'DINING'), ('SHOP', 'SHOPPING'), ('ATTR', 'ATTRACTION')], max_length=4)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
