# Generated by Django 4.0.6 on 2022-07-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_dummyuser'),
        ('trips', '0002_alter_trip_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='profiles.dummyuser'),
        ),
    ]
