# Generated by Django 4.0.6 on 2022-07-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.trip'),
        ),
    ]
