# Generated by Django 4.0.6 on 2022-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
