# Generated by Django 4.0.6 on 2025-04-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('DINE', 'Dining'), ('SHOP', 'Shopping'), ('ATTR', 'Attraction')], max_length=4),
        ),
    ]
